### ISSUE TITLE
Adoption of SHA-256 over SHA-1 for Cryptographic Applications

### ISSUE THREAD

**Issue by theblackethiopiandude** [Thejas-p-karkera/Register-Login-System#1]
I propose transitioning from SHA-1 to SHA-256 for cryptographic hashing in the current project. 

**Background:**
SHA-1 has known vulnerabilities, including collision attacks, undermining its security. Transitioning to SHA-256 enhances security.
Find more about SHA-1 [here](https://cyberw1ng.medium.com/secure-hash-algorithm-1-sha-1-a-comprehensive-overview-2023-7be2ca9a06eb#:~:text=While%20SHA%2D1%20was%20once,produce%20the%20same%20hash%20value).

**Benefits:**
- Strengthened security and data integrity
- Mitigation of risks associated with SHA-1 vulnerabilities
- Alignment with industry best practices

**Action:**
I suggest updating the repository's cryptographic hashing to SHA-256 for enhanced security.

Thank you,

**Comment by Thejas-p-karkera** [comment]
Thank you for your insightful feedback regarding the transition from SHA-1 to SHA-256 for cryptographic hashing in the project. I understand the importance of this change in enhancing security and aligning with industry best practices.

I have implemented the suggested changes in the project. The repository's cryptographic hashing has been updated to SHA-256. I have tested the changes and ensured that they are working as expected.

I appreciate your valuable feedback as it has helped improve the security of the project. Please feel free to review the changes and let me know if there are any other areas that need improvement.

Best Regards,
Thejas

**Comment by theblackethiopiandude** [comment]
I'm glad to hear that the suggested changes have been successfully implemented, and the repository's cryptographic hashing has been updated to SHA-256.I appreciate your proactive approach and dedication to improving the project. If there are any other areas that require assistance or attention, please don't hesitate to reach out.

**Comment by mahid712** [comment]
@Thejas-p-karkera Hey I am a student from mgm I wanted to discuss with you about the mgm-website repository which you have ,if you are ok with discussing about it then you can send me a message on my insta it's 
Heyy.mahid 
Or you could leave me a message with your insta I will send you message from my side .it's not much that I would discuss only some things related with my personal project which I am doing.
Thank you .
